config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :order_items
  resource :cart, only: [:show]
  resources :charges
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :update_total
    before_create :update_status

    def calculate_total
      self.order_items.collect { |item| item.product.price * item.quantity }.sum
    end

    private

    def update_status
      if self.status == nil?
        self.status = "In progress"
      end
    end

    def update_total
      self.total_price = calculate_total
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
      @order_items = current_order.order_items
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
      @order_items = current_order.order_items
  end

  def create
  # Amount in cents
  @amount = current_order.total_price.to_i

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @response = JSON.parse(Bestseller.get_bestseller_list)
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
    <% @order_items.each do |item| %>
      <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
      <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
    <% end %>
    <p>Your Total: <%= number_to_currency current_order.total_price %></p>
  <% else %>
    <p>Your shopping cart is empty.</p>
  <% end %>
  

app/views/charges/create.html.erb
<h2>Thanks, you paid <%= number_to_currency current_order.total_price %>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency current_order.total_price %></p></span>
    </label>
  </article>
  <% if @order_items.any? %>
      <% @order_items.each do |item| %>
        <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
        <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
      <% end %>
      <p>Your Total: <%= number_to_currency current_order.total_price %></p>
    <% else %>
      <p>Your shopping cart is empty.</p>
    <% end %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount='<%= number_to_currency current_order.total_price %>'
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
   <p><%= product.name %> | <%= number_to_currency product.price %>
   <%= form_for @order_item do |f| %>
     <%= f.hidden_field :product_id, value: product.id %>
     <%= f.number_field :quantity %>
     <%= f.submit "Add to cart" %>
   <% end %></p>
 <% end %>



<h1>Api Area</h1>
<table>
  <thead>
  <th>Title</th>
  <th>Authors</th>
</thead>
<tbody>
  <% @response["results"]["books"].each do |book| %>
  <td><%=book["title"]%></td>
  <td><%=book["author"]%></td>
  <% end %>
</tbody>
</table>